services:
  postgres:
    image: postgres:17
    container_name: postgres-vet-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pets-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres

  frontend:
    build: 
      context: ../AS 
      dockerfile: ../AS/Dockerfile
    container_name: pets-frontend
    ports:
      - "3000:3000" # Cambia el puerto según tu configuración de frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080 # O la URL correspondiente a tu API 

volumes:
  postgres-data:
    driver: local
